### ISSUE TITLE
#bug 阅读无法打开书籍

### ISSUE THREAD

**Issue by ChengJieping** [anlingyi/xechat-idea#62]
![image](https://user-images.githubusercontent.com/34883841/183791917-7afaa8f5-d4f4-459f-82cd-66ba0f95d537.png)
1.6.2版本 点击书籍无法打开阅读界面

**Comment by anlingyi** [comment]
刚经过测试，1.6.2-beta更新之后，首次使用阅读功能，会出现无法打开书籍的问题，如无其它报错，请尝试使用命令 #over 结束阅读，然后重新使用命令 #open 0 打开阅读，看是否可以成功进入阅读界面，感谢反馈！

**Comment by ChengJieping** [comment]
您好，您的邮件已收到，谢谢！

**Comment by JIAZoro** [comment]
txt文件因为无法生成目录，无法添加书籍

**Comment by anlingyi** [comment]
> txt文件因为无法生成目录，无法添加书籍

小说目录格式可以发一下吗？因为是通过正则提取的目录，可以尝试更改下正则表达式，感谢！

**Comment by JIAZoro** [comment]
> > txt文件因为无法生成目录，无法添加书籍
> 
> 小说目录格式可以发一下吗？因为是通过正则提取的目录，可以尝试更改下正则表达式，感谢！

正文 第一章

    第一章


    ——他竟忘了，自己一行是奉旨来恭贺世子喜诞的。
------------

正文 第二章

    第二章

    在浙江，经过一个冬季的枯水季节，桃花汛也过了，农历四月，新安江水便到了水量最为充沛，慷慨地从它流经的各个堰口浇灌两岸无边稻田青苗的时节。江水而且是如此澄澈平静，不禁使人联想到《道德经》上那句“上善若水”的箴言，顿生无穷的感恩之思。

**Comment by anlingyi** [comment]
@JIAZoro 目录格式没问题，目前的正则是可以支持解析的，解析不出来可能是别的问题

**Comment by anlingyi** [comment]
@JIAZoro 可以向群里反馈问题：754126966，该功能的作者是 ”打工人“

**Comment by ChengJieping** [comment]
问题已解决，txt文件内容首行是空行，导致无法打开书籍
