### ISSUE TITLE
关于用户id唯一性bug

### ISSUE THREAD

**Issue by smilesnake** [anlingyi/xechat-idea#70]
服务端生成用户id是通过ChannelAction.getId(ctx),而此方法使用的是channel.id().asShortText()。
netty的官方文档表明asShortText()是简短但全局非唯一的字符串。这与用户id唯一性冲突
可能会在缓存用户信息时key值冲突，将会替换旧的用户缓存信息

**Comment by anlingyi** [comment]
感谢提醒
