### ISSUE TITLE
请教一下,idea插件开发,可以在插件中启动一个http服务吗

### ISSUE THREAD

**Issue by golyu** [anlingyi/xechat-idea#88]
如题,目前开发一个插件,遇到个困扰的问题,vscode插件是允许的,idea查阅了很多资料,没发现类似项目

**Comment by anlingyi** [comment]
理论上来说应该是可以的

**Comment by anlingyi** [comment]
> 

具体遇到的是什么问题呢？端口问题还是其它什么问题...

**Comment by golyu** [comment]
> 么问题呢？端口问题还是其它什么问题...

感谢回复,已经解决了,不是插件的问题,是我引入了ktor,而ktor主要是做后端的框架,他依赖一个入口,我找到插件的全局ApplicationService作为入口后,成功的启动了http服务

**Comment by washmore** [comment]
好思路啊  这样的话 能把鱼塘直接集成到插件端,增加一个插件选项开关是否开启内置的服务端就行了

**Comment by anlingyi** [comment]
> 好思路啊 这样的话 能把鱼塘直接集成到插件端,增加一个插件选项开关是否开启内置的服务端就行了,直接就能打局域网

登录的时候可以指定服务端地址的，像这样：#login 你的昵称 -h 127.0.0.1 -p 1024
